### PR TITLE
Job/ALARMiator

### PR DESCRIPTION
**Pull request by ForrestFalcon**
This PR adds the ALARMiator job from @BoxSo

### CODE REVIEW

**Comment by KirschbaumP** [comment]
Can you bring the two commits together to one?

**Comment by ForrestFalcon** [comment]
Yes, I will do a "Squash and merge". But I split the two commits because the first one is the official PR from @BoxSo and the second PR are my changes. So he can look what I changed.

**Comment by BoxSo** [comment]
Changes look good, will do the housekeeping next time before sending a pull request! :)

**Comment by BoxSo** [comment]
Thanks!

**Pull request merged**
